# Generated by Django 4.2.20 on 2026-02-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cal_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.CharField(max_length=50)),
                ('num2', models.CharField(max_length=50)),
                ('op', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=50)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
